apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lvwgj39jp-python
  janus-idp.io/tekton: lvwgj39jp-python
  backstage.io/kubernetes-id: lvwgj39jp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lvwgj39jp-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
